#! /bin/sh

sxhkd &
compton --config $HOME/.config/compton/compton.conf &
dunst &
~/.config/bspwm/panel.sh &
pasystray &
nm-applet &
feh --bg-fill /home/lucas/Downloads/wp2003009.jpg &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           2
bspc config top_padding          20
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#### BSPWM coloring ####
bspc config normal_border_color     "#4c566a"
bspc config active_border_color     "#1e1e1e"
bspc config focused_border_color    "#5e81ac"
bspc config presel_feedback_color   "#5e81ac"
bspc config urgent_border_color     "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)

bspc rule -a '*:zathura' state=tiled
setxkmap -model pc101 -layout br
