#! /bin/sh
sxhkd &
compton --config $HOME/.config/compton/compton.conf &
dunst &
$HOME/.config/bspwm/panel.sh &
pasystray &
nm-applet &
$HOME/.fehbg &

# might have to adjust these values according to current setup, will add a script to handle that int the future
# TODO
xrandr --output DisplayPort-0 --off --output DisplayPort-1 --off --output DisplayPort-2 --off --output HDMI-A-0 --primary --mode 2560x1080 --pos 0x0 --rotate normal --output DVI-D-0 --mode 1920x1080 --rate 60 --pos 2560x0 --rotate normal
bspc monitor HDMI-A-0 -d 1 2 3 4 5 6
bspc monitor DVI-D-0  -d 7 8 9 10

bspc config border_width         2
bspc config window_gap           0
bspc config top_padding          20
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#### BSPWM coloring ####
bspc config normal_border_color     "#4c566a"
bspc config active_border_color     "#1e1e1e"
bspc config focused_border_color    "#5e81ac"
bspc config presel_feedback_color   "#5e81ac"
bspc config urgent_border_color     "#dd2727"

bspc rule -a '*:zathura' state=tiled
bspc rule -a firefoxdeveloperedition:Toolkit sticky=on state=floating
