general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on && pkill -SIGUSR1 waybar
}

# Lock after 10 min
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# Screen off after 15 min
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
