#!/bin/bash

bspc config border_width         1
bspc config window_gap           0
bspc config top_padding          20
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config focus_follows_pointer true

bspc config normal_border_color     "#282828"
bspc config active_border_color     "#928374"
bspc config focused_border_color    "#928374"
bspc config presel_feedback_color   "#98971a"
bspc config urgent_border_color     "#cc241d"

bspc rule -a Zathura state=tiled
bspc rule -a Peek state=floating
bspc rule -a Bitwarden state=floating
bspc rule -a firefoxdeveloperedition:Toolkit sticky=on state=floating
bspc rule -a emacs state=tiled

$HOME/.config/screen-layout/screen-layout.sh

if [[ $(xrandr | grep ' connected' | wc -l) -eq 3 ]]; then
  bspc monitor DisplayPort-0 -d 1 2
  bspc monitor HDMI-A-1 -d 3 4 5 6
  bspc monitor HDMI-A-0  -d 7 8 9 10
elif [[ $(xrandr | grep ' connected' | wc -l) -eq 2 ]]; then
  bspc monitor HDMI-A-0 -d 1 2 3 4 5 6
  bspc monitor HDMI-A-1  -d 7 8 9 10
else
  bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 10
fi

$HOME/.config/polybar/panel.sh
